services:
  - type: web
    name: backend-waste-collection-management
    runtime: node
    rootDir: Backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PAYPACK_CLIENT_ID
        sync: false
      - key: PAYPACK_CLIENT_SECRET
        sync: false
      - key: PAYPACK_WEBHOOK_SECRET
        sync: false
